# Schema for the configuration files of the Views Alias Filter module.
views_alias_filter.settings:
  type: config_object
  label: 'Views Alias Filter settings'
  mapping:
    example:
      type: string
      label: 'Example'
